menu:
  归档: /archives
rss: /atom.xml
description:
# social:
  # weibo: #http://weibo.com/ikeson
  #github: https://github.com/maxslin
  #stack_overflow:
  #facebook:
  #twitter: #https://twitter.com/skx926
  #google_plus: #https://plus.google.com/118328736821069549236
  #instagram: #https://www.instagram.com/skx926

page_comment: true
logo: /images/avatar.png
background:
  cover: /images/background-cover2.jpg
  color: cover-purple

fancybox: true

cloudtie_productkey: 7e456de65fb945698c448c72191454ce

google_analytics: UA-73055515-1

favicon: /images/favicon1.png
